# Regresión lineal simple en Python

### Primer commit

In [2]:
import pandas as pd
import numpy as np

C:\Users\Jose\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Jose\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
C:\Users\Jose\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
data = pd.read_csv("Advertising.csv",sep=",")
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
import statsmodels.formula.api as smf
lm = smf.ols(formula="Sales~TV", data = data).fit()
lm.params

Intercept    7.032594
TV           0.047537
dtype: float64

El modelo lineal predictivo sería: Sales = 7.032594 + 0.047537 * TV

In [5]:
data["sales_pred"] = 7.032594 + 0.047537*data["TV"]
data

TV  Radio  Newspaper  Sales  sales_pred
0    230.1   37.8       69.2   22.1   17.970858
1     44.5   39.3       45.1   10.4    9.147990
2     17.2   45.9       69.3    9.3    7.850230
3    151.5   41.3       58.5   18.5   14.234450
4    180.8   10.8       58.4   12.9   15.627284
..     ...    ...        ...    ...         ...
195   38.2    3.7       13.8    7.6    8.848507
196   94.2    4.9        8.1    9.7   11.510579
197  177.0    9.3        6.4   12.8   15.446643
198  283.6   42.0       66.2   25.5   20.514087
199  232.1    8.6        8.7   13.4   18.065932

[200 rows x 5 columns]

In [6]:
sales_pred = lm.predict(pd.DataFrame(data["TV"]))
sales_pred

0      17.970775
1       9.147974
2       7.850224
3      14.234395
4      15.627218
         ...    
195     8.848493
196    11.510545
197    15.446579
198    20.513985
199    18.065848
Length: 200, dtype: float64

In [7]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Sat, 09 Sep 2023   Prob (F-statistic):           1.47e-42
Time:                        15:18:03   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""